git-appraise/git-appraise.go
The %q format specifier is [defined as](https://golang.org/pkg/fmt/):
%q	a double-quoted string safely escaped with Go syntax
It essentially exists so you don't have to manually escape strings when printing them. See for yourself:
http://play.golang.org/p/zFZzzfpP1g
=> Replace \"%s\" with %q in printfs

commands/show.go, repository/mock_repo.go, repository/repo.go
There are more things the lint tool picks up, however some changes would mean
making changes to parts of the public API for a package, i.e. for reviews the
lint tool suggests changing GetJson() to GetJSON().
=> Small tweaks to satisfy the go lint tool

commands/comment.go
This commit requires that for a comment, if -lgtm AND -nmw have not been set a
comment must be.
As per https://github.com/google/git-appraise/issues/8#issuecomment-165078292
=> Added error message for leaving empty comments

commands/comment.go, repository/git.go, repository/mock_repo.go, repository/repo.go
For review comments, the absense of the -m flag will now attempt to load the
user's default git editor.
i.e. git appraise comment c0a643ff39dd
An initial draft as discussed in #8 
I'm still not sure whether or not the file that is saved is in the most appropriate place or not. I like the idea of it being relative to the project although it could have gone in `/tmp` I suppose.
=> Force default git editor when omitting -m

review/review.go
This is a proposed fix to #22 
`updateThreadsStatus` was not actually updating the CommentThread instances, but updating copies thereof.
=> Fixed updateThreadsStatus to modify original thread instances, rather than modifying copies

commands/commands.go, commands/comment.go, commands/reject.go
The reject subcommand adds a NMW comment to the review. Unlike
the accept subcommand, this requires a comment. The -m flag can
be passed to do this, or if no flag is passed it will open the
default git text editor.
This is what I have in mind in regards to #17
=> Added a reject subcommand

commands/commands.go, commands/comment.go, commands/reject.go
This isn't really a big deal, it was just bugging me from when I first
wrote it. Tidies the code up a bit and means we don't have to declare
the file name twice.
=> Using the same constant for the comment file name

commands/submit.go, repository/git.go, repository/mock_repo.go, repository/repo.go
I've made a start on what you suggested in #35. It seems to work
as expected. Adding a --merge flag when git is configured to rebase for example
will overwrite the rebase configuration.
This will fallback to 'merge' by default as I believe it did before.
Is this the kind of thing you were after?
=> Implemented a way to configure submissions

commands/comment.go
```
$ git appraise comment -m test -f README.md -l 1 b2a042b3773555f73aef5a840289b3ca110612de
Unabled to comment on the given location: Line number 1 does not exist in file "README.md"
```
line-number should be started from 1.
=> Fix line-number

git-appraise/git-appraise.go
As stated in #42, this will now show open reviews and not the usage text.
I'm still a little unsure about this, because the list command is obviously
still there and will work with flags, -a and --json for example.
Should this (non-subcommand version) allow the same, and if so, do we even need
the list subcommand?
/cc @jishi9
=> git-appraise without subcommand will list reviews

commands/comment.go, commands/input/input.go
I've gathered a few thoughts in regards to #56 in the form of this commit. This
currently doesn't take in to account stdin (-), just a file name.
Basically, the user has 3 choices as this point:
- 1 git appraise comment -m "nice code!" HASH
- 2 git appraise comment HASH
- 3 git appraise comment -F message HASH
Given that 'message' is the file name that contains the message. As for the
stdin, keeping that similar to git would be a good idea. They present the user
with the following output and then read:
```
if (isatty(0))
fprintf(stderr, _("(reading log message from standard input)\n"));
read_from_stdin(&log);
```
This would be consistent and imo seems like it could work well. I agree with
@ojarjur in that this should be supported with accept, comment, reject
and request. This commit only …
=> Accepting -F flag on git-appraise comments

commands/comment.go, commands/input/input.go, commands/request.go, commands/request_test.go
As mentioned in #56, passing - for stdin with -F will now read. This is
partially inspired by how git approaches this issue. Here are a couple of
examples of how comments can be made as of this commit:
```
echo 'hello!' | git appraise comment -F - HASH
git appraise comment -F - HASH
(reading comment from standard input)
hello!
```
(ctrl+D to exit from the attached version)
Feedback / thoughts would be appreciated! :)
=> Allowing stdin in the case of comment -F

repository/git.go, repository/git_test.go, repository/mock_repo.go, repository/repo.go, review/review.go
1. Add a `GetAllNotes` method to the Repo interface. This reads the
contents for all git-notes under the given ref in a single batch
operation. This is faster than the old method because we only
shell out to the git command a fixed number of times rather than
doing so repeatedely for every single review.
2. When checking each review to see if it has been submitted, cache
the set of commits reachable from each target ref, and use that
for determining submitted status. This saves us from having to
reperform the (linear) scan of the git history for every review.
With these changes, listing the reviews for the git-appraise repo
drops from taking ~2 seconds to ~0.15 seconds.
For one particular test repo, with 15k reviews, this drops the list
latency from 48 minutes to 6 seconds.
=> Two substantial performance improvements for listing reviews:

commands/commands.go, commands/pull.go, commands/push.go, commands/rebase.go, commands/request.go, commands/submit.go, repository/git.go, repository/mock_repo.go, repository/repo.go, review/request/request.go, review/review.go, review/review_test.go, schema/request.json
This change improves the support for rebasing reviews in multiple ways:
1. Adding a new `refs/archives/devtools` ref that can be used to make sure that commits which have been rebased do not get garbage collected.
2. Adding a new `alias` field to the request schema that enables tracking review history across rebases.
3. Adding a new `rebase` subcommand that enables us to update the history for a change prior to submitting it.
=> Better support for rebasing reviews

review/review.go
This is intended for users of git-appraise as a library so that
they do not have to figure out the right logic for listing commits
based on the already provided building blocks (GetBaseCommit
and GetHeadCommit).
=> Add a ListCommits method for reviews.

review/review.go
This change improves the loading of reviews in two ways:
1. Do not return a nil error from `getSummaryFromNotes` if the returned
summary is nil, as that breaks assumptions made by callers that one
of the two return values must be non-nil.
2. Proactively check that the specified hash exists and points to a commit
object before trying to load a review attached to that commit.
The combination of these two changes fixes #73
The first change prevents the tool from panicing on a bad input, while
the second change makes the error message presented to the user easier
to understand and fix.
=> Validate review hashes when loading a review.

commands/comment.go, commands/output/output.go, review/analyses/analyses.go, review/comment/comment.go, schema/comment.json
The review format from ShipeShape supports fulle specification
of a block of text withint a file. We implement this by allowing
the cli to take a range specified as:
`startLine[+startColumn][:endLine[+endColumn]]`
We need to fully check the semantics of the specified location.
Lines and columns are number from 1 -> max(uint32). The start must
be before the start of the file.
=> Implement full source file range support

commands/output/output.go, review/comment/comment.go, review/review.go, review/review_test.go, schema/comment.json
This change adds read-only support for comment edit actions. These
are represented in the JSON format using a new "original" field that
references the original, unedited comment.
By default, when displaying a comment thread that has been edited,
only the current version of comment is displayed. The full history of
the comment can be viewed by adding the `--json` flag to the
`git appraise show` command, to display the review in JSON format.
This change defines how edits are represented in git-notes and makes
the tool properly display edited comments, but does not add any support
to the tool for creating edits.
This fixes #67
=> Support edited comments.

commands/abandon.go, commands/accept.go, commands/comment.go, commands/pull.go, commands/rebase.go, commands/reject.go, commands/request.go, commands/submit.go, repository/git.go, repository/mock_repo.go, repository/repo.go, review/comment/comment.go, review/gpg/signable.go, review/request/request.go, review/review.go, review/review_test.go
Addresses #89 
Hey there!
Here's my work so far w.r.t. implementing signing and verification. As it stands now, signing is available for both requests and acceptances, and we can verify those at `pull` time. I wanted to share now to see if there were any major contentions with the path I've gone down before I went through the rote repetition of adding signing functionality to the other comment-based commands.
Cheers!
=> Adds GPG signing and verification

.github/workflows/mirror-pull-requests.yaml
The default behavior of the GitHub workflow is to only fetch the last
commit of the current branch (resulting in a shallow repository).
This causes issues for the workflow to mirror pull request metadata
into git-notes, as the full history of the repository is necessary
in order for that to work.
This change fixes that by modifying the local repository to no longer
be a shallow clone.
=> Make the PR-mirroring workflow use the entire history of the current branch

.github/workflows/mirror-pull-requests.yaml, repository/git.go, repository/mock_repo.go, repository/repo.go
This change cleans up the API for low-level repository operations
in the following ways:
1. Introduce more generic operations on the underlying repository
DAG objects (i.e. blobs, trees, commits, and refs).
2. Fix a bug in the code for merging archives where we did not
check if the local archives ref existed before trying to
resolve it.
Previously, the API exposed by the `repository` interface was very
tailored to the tasks that the git-appraise needed to perform for
code reviews. That meant that adding new features which used the
repository in slightly different ways would require rather large
changes to the repository interface.
Under the new API, any feature that simply relies upon the
features of git should be able to use the API without changes.
This was originally part of the pull …
=> Cleanup and generalize the API for low-level repository operations.

repository/git.go
On Windows, the current working directory is searched for a matching executable before the rest of the user's path.
This causes a potential issue where running `git appraise` from within a directory that has an executable file matching the command `git` will cause that (untrusted) file to be invoked instead of the expected `git` executable when `git-appraise` attempts to shell out to `git`.
This change prevents that by using the new `execabs` package instead of `os/exec`. With this change, that scenario would cause `git appraise` to report an error rather than invoking the wrong `git` binary.
More background on the related issue [here](https://blog.golang.org/path-security)
=> Require `git` to be run from a trusted path

.github/workflows/build-and-test.yaml, .github/workflows/mirror-pull-requests.yaml, go.mod, go.sum
The new GitHub action replaces the old Travis CI-based build and test.
This also sets up the `go.mod` and `go.sum` files which was necessary to (easily) get the build/test working.
Fixes #104
=> Add a github action to build and test
